//Generated by SceneFind.cs 
using UnityEditor; 
namespace GameCore.UEditor { 
public class EditorMapOpener : Editor { 
	[UnityEditor.MenuItem("Open Scene/Main Menu", false, 20)]
	private static void MainMenu() {
		OpenIf("Assets/Scenes/MainMenu.unity");
	}
	[UnityEditor.MenuItem("Open Scene/Scene", false, 20)]
	private static void scene() {
		OpenIf("Assets/scene.unity");
	}
	private static void OpenIf(string level) {
		if (EditorApplication.SaveCurrentSceneIfUserWantsTo()){
			EditorApplication.OpenScene(level);
		}
	}
}
}